name: solo8
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip 
  - pip:
    - git+https://github.com/samaloney/stixpy
    - spacepy
    - solo-epd-loader
    - ipykernel
    - sunpy[all]
    - reproject
    - sunpy-soar
    - ipywidgets
    - astroquery
    - sunraster
    - jupyterlab


